spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camunda
    username: bpms
    password: password

keycloakClientId: camunda-cockpit
admin-realm.client-secret: secret
keycloakAdminUrl: http://localhost:8088/auth/realms/master
keycloakcCamundaPluginAdminUrl: http://localhost:8088/auth/admin/realms/master

data-platform:
  kafka:
    bootstrap: localhost:9092
    ssl:
      enabled: false

logging:
  level:
    root: "info"
    org.springframework.web: "debug"
  file:
    name: ./logs/${spring.application.name}.log
  pattern:
    #    Logging patterns inherited from Spring Boot default logging system configuration
    console: '%d{${LOG_DATEFORMAT_PATTERN}} [trace:%X{traceId}/%X{spanId}/%X{x-request-id}] ${LOG_LEVEL_PATTERN} %pid --- [%15.15t] %-40.40c{1.} : %m%n${LOG_EXCEPTION_CONVERSION_WORD}'
    file: '%d{${LOG_DATEFORMAT_PATTERN}} ${LOG_LEVEL_PATTERN} %pid --- [%t] %-40.40c{1.} : %m%n${LOG_EXCEPTION_CONVERSION_WORD}'