apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ .Values.keycloak.clientName }}
  labels:
  {{- include "jenkins-operator.metaLabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
  namespace: {{ .Release.Namespace }}
spec:
  clientId: {{ .Values.keycloak.clientName }}
  public: false
  directAccess: false
  audRequired: false
  secret: {{ .Values.keycloak.secretName }}
  advancedProtocolMappers: false
  serviceAccount:
    clientRoles: null
    enabled: true
    realmRoles:
      - camunda-admin
  webUrl: {{ template "jenkins-operator.jenkinsUrl" . }}
  targetRealm: {{ template "keycloak.realm" . }}