apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bus-proc-adm-portal-{{ .Values.namespace }}
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: bus-proc-adm-portal-{{ .Values.namespace }}
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      path: {{ .Values.prometheusScrapePath }}
      scheme: http
      targetPort: {{ .Values.service.port }}
  jobLabel: app
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
